name: studymate
description: "Study Mate Project"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # Existing dependencies with 'any' versions remain unchanged
  firebase_auth: any
  cloud_firestore: any
  image_picker: any
  firebase_storage: any
  firebase_core: any
  http: any
  cupertino_icons: any
  flutter_font_icons: any
  hive: any
  hive_flutter: any
  path_provider: any
  google_fonts: any
  google_nav_bar: any
  dropdown_button2: any
  flutter_cached_pdfview: any
  lottie: any
  intl: any
  google_generative_ai: any
  permission_handler: any
  flutter_downloader: any
  flutter_slidable: any
  timezone: any
  firebase_messaging: any
  firebase_in_app_messaging: any

  # Packages that require specific versions
  share_plus: any
  # syncfusion_flutter_pdfviewer: any
  flutter_pdfview: any
  fl_chart: any
  flutter_markdown: any
  shimmer: any
  percent_indicator: any
  flutter_local_notifications: any

  # Updated url_launcher dependencies
  url_launcher: any # Updated to the latest version compatible with Dart SDK 3.5.3
  url_launcher_linux: any # Added with a compatible version
  syncfusion_flutter_pdfviewer: ^28.1.38
  go_router: any

dev_dependencies:
  flutter_lints: any # Updated to a version compatible with Dart SDK 3.5.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/img/GameCharacters/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
